name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y tar xz-utils
        
    - name: Make build script executable
      run: chmod +x build-package.sh
      
    - name: Build package
      run: ./build-package.sh
      
    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: supermicro-ipmi-plugin
        path: supermicro-ipmi-1.0.0.txz
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: supermicro-ipmi-1.0.0.txz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 